### ISSUE TITLE
a question about comyco

### ISSUE THREAD

**Issue by linnaeushuang** [thu-media/Comyco#4]
Thank you for your work.
I have a question about your paper. 
In section 4.2,the ideas and formulas used by your `instant solver` are not much different from the MPC(cite 51).Intuitively,comyco should not be better than MPC,if you use imitation learning.In your results,comyco is better than MPC.why is that?any other tips?

thanks.

**Comment by godka** [comment]
Thank to follow our work. It's a good question.
We have explained the key idea of the instant solver in Sec. 4.2: The key idea is to choose future chunk k’s bitrate Rk by taking N steps ahead via an offline virtual player, and solves a specific QoE maximization problem with **future network throughput measured**.
In contrast, MPC leverages the estimated throughput rather than future throughput.
That's the key difference between MPC and instant solver.

**Comment by godka** [comment]
The key motivation of utilizing future **real** throughput rather than the estimated throughput is that recent work neglects exogenous inputs zt (e.g. future throughput measured) when estimating policy gradient, since the advantage function may be overestimated or underestimated (V(st;θv)≠V(st,zt;θv)). On the contrary, Comyco considers zt as the future throughput and outputs at=max_a[QoE(st, at,zt](See Eq.2). Same conclusions and proofs please refer to [a]:§3. 

[a]Mao et.al., Variance Reduction for Reinforcement Learning in Input-Driven Environments, ICLR 19', May 2019.
